version: "3"

services:
  wordpress:
    image: wordpress:latest # https://hub.docker.com/_/wordpress/
    container_name: project_creativecommons-wordpress
    ports:
      - 8080:80
    volumes:
      #- ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      # Full wordpress project
      #- ./wp-app:/var/www/html
      # Plugin development
      - ./wp-plugin-creativecommons-website/:/var/www/html/wp-content/plugins/wp-plugin-creativecommons-website
      # Theme development
      - ./creativecommons-base/:/var/www/html/wp-content/themes/creativecommons-base
      - ./wp-theme-creativecommons.org/:/var/www/html/wp-content/themes/wp-theme-creativecommons.org
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_NAME: "${DB_NAME:-wordpress_db}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD:-db_password}"
    depends_on:
      - database
    networks:
      - backend
  database:
    build:
      # change db if required in .env file
      context: ./database/${DATABASE:-mariadb}
    container_name: project_creativecommons-database
    ports:
      - 3306:3306
    volumes:
      #- ./wp-data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DB_NAME:-wordpress_db}"
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD:-db_password}"
    networks:
      - backend

volumes:
  db_data:

networks:
  backend: